-- ══════════════════════════════════════════════════════════════════
-- ITAM POC — Seed Data
-- Run after migrations: supabase db seed
-- ══════════════════════════════════════════════════════════════════

-- ── SITES ──
INSERT INTO public.sites (id, name, city, country, timezone, contact_email) VALUES
('MM',  'Main Metro HQ',       'New York',     'US', 'America/New_York',     'it.mm@company.com'),
('ATL', 'Atlanta Hub',          'Atlanta',      'US', 'America/New_York',     'it.atl@company.com'),
('AVN', 'Avon Office',          'Avon',         'US', 'America/New_York',     'it.avn@company.com'),
('CHD', 'Chad Operations',      'N''Djamena',   'TD', 'Africa/Ndjamena',     'it.chd@company.com'),
('HRE', 'Harare Office',        'Harare',       'ZW', 'Africa/Harare',       'it.hre@company.com'),
('PSE', 'Palestine Office',     'Ramallah',     'PS', 'Asia/Hebron',         'it.pse@company.com'),
('PLD', 'Poland Branch',        'Warsaw',       'PL', 'Europe/Warsaw',       'it.pld@company.com'),
('WLD', 'Wildlands Depot',      'Denver',       'US', 'America/Denver',      'it.wld@company.com');

-- ── ASSET CATEGORIES ──
INSERT INTO public.asset_categories (name, description, useful_life_years) VALUES
('End User Computing',  'Laptops, desktops, tablets assigned to users',     4),
('Infrastructure',      'Servers, networking equipment, UPS systems',       7),
('Peripheral',          'Printers, scanners, projectors',                   5),
('Network',             'Switches, routers, access points, firewalls',      6),
('Power',               'UPS, power distribution, generators',              8),
('Display',             'Monitors, projectors, digital signage',            5);

-- ── ASSET TYPES ──
INSERT INTO public.asset_types (name, category_id, icon) VALUES
('Laptop',          1, 'laptop'),
('Desktop',         1, 'monitor'),
('Tablet',          1, 'tablet'),
('Server',          2, 'server'),
('Printer',         3, 'printer'),
('Scanner',         3, 'scan'),
('Projector',       6, 'projector'),
('Monitor',         6, 'monitor'),
('Phone',           1, 'smartphone'),
('Network Switch',  4, 'network'),
('Router',          4, 'wifi'),
('UPS',             5, 'battery-charging'),
('Access Point',    4, 'wifi'),
('Firewall',        4, 'shield');

-- ── MANUFACTURERS ──
INSERT INTO public.manufacturers (name, website, support_email) VALUES
('Dell',        'https://dell.com',         'support@dell.com'),
('HP',          'https://hp.com',           'support@hp.com'),
('Lenovo',      'https://lenovo.com',       'support@lenovo.com'),
('Apple',       'https://apple.com',        'support@apple.com'),
('Cisco',       'https://cisco.com',        'support@cisco.com'),
('Samsung',     'https://samsung.com',      'support@samsung.com'),
('Microsoft',   'https://microsoft.com',    'support@microsoft.com'),
('Logitech',    'https://logitech.com',     'support@logitech.com'),
('APC',         'https://apc.com',          'support@apc.com'),
('Ubiquiti',    'https://ui.com',           'support@ui.com');

-- ── DEPARTMENTS (per site) ──
INSERT INTO public.departments (name, site_id) VALUES
('IT',          'MM'),  ('Finance',    'MM'),  ('HR',         'MM'),  ('Operations', 'MM'),
('IT',          'ATL'), ('Finance',    'ATL'), ('Operations', 'ATL'),
('IT',          'AVN'), ('Finance',    'AVN'),
('IT',          'CHD'), ('Operations', 'CHD'),
('IT',          'HRE'), ('Finance',    'HRE'), ('HR',         'HRE'), ('Operations', 'HRE'),
('IT',          'PSE'), ('Operations', 'PSE'),
('IT',          'PLD'), ('Finance',    'PLD'), ('Operations', 'PLD'),
('IT',          'WLD'), ('Operations', 'WLD');

-- ── SAMPLE ASSETS (50 across sites) ──
-- Auto-IDs will be generated by the trigger
INSERT INTO public.assets (serial_number, mac_address, hostname, ip_address, manufacturer_id, model, specifications, asset_type_id, category_id, site_id, department_id, custodian_name, purchase_date, purchase_value, warranty_expiration, status, condition, antivirus_status) VALUES
-- MM (Main Metro) — 12 assets
('SN-MM-001', '00:1A:2B:3C:4D:01', 'MM-LAP-001', '10.1.1.10', 1, 'Dell Latitude 5540',      '16GB RAM, 512GB SSD, i7-1365U',     1, 1, 'MM', 1, 'John Smith',      '2024-03-15', 1450.00, '2027-03-15', 'active', 'good', 'protected'),
('SN-MM-002', '00:1A:2B:3C:4D:02', 'MM-LAP-002', '10.1.1.11', 3, 'Lenovo ThinkPad X1 Carbon','16GB RAM, 512GB SSD, i7-1365U',     1, 1, 'MM', 1, 'Sarah Jones',     '2024-01-10', 1680.00, '2027-01-10', 'active', 'new', 'protected'),
('SN-MM-003', '00:1A:2B:3C:4D:03', 'MM-DSK-001', '10.1.1.12', 2, 'HP EliteDesk 800 G9',      '32GB RAM, 1TB SSD, i9-13900',       2, 1, 'MM', 1, 'Mike Chen',       '2023-06-20', 1890.00, '2026-06-20', 'active', 'good', 'protected'),
('SN-MM-004', '00:1A:2B:3C:4D:04', 'MM-SRV-001', '10.1.1.100','1', 'Dell PowerEdge R750xs',   '128GB RAM, 4x2TB SSD RAID',         4, 2, 'MM', 1, 'IT Department',   '2023-01-05', 8500.00, '2028-01-05', 'active', 'good', 'not_applicable'),
('SN-MM-005', '00:1A:2B:3C:4D:05', 'MM-PRT-001', '10.1.1.50', 2, 'HP LaserJet Pro M428fdn',  'Duplex, Network, Scan',             5, 3, 'MM', 2, 'Finance Dept',    '2022-11-01', 420.00,  '2025-11-01', 'active', 'fair', 'not_applicable'),
('SN-MM-006', '00:1A:2B:3C:4D:06', 'MM-MON-001', '10.1.1.13', 1, 'Dell U2723QE',             '27" 4K USB-C Hub Monitor',          8, 6, 'MM', 1, 'John Smith',      '2024-03-15', 550.00,  '2027-03-15', 'active', 'new', 'not_applicable'),
('SN-MM-007', '00:1A:2B:3C:4D:07', 'MM-LAP-003', '10.1.1.14', 4, 'Apple MacBook Pro 14"',    '18GB RAM, 512GB SSD, M3 Pro',       1, 1, 'MM', 3, 'Lisa Wang',       '2024-06-01', 2200.00, '2027-06-01', 'active', 'new', 'protected'),
('SN-MM-008', '00:1A:2B:3C:4D:08', 'MM-SWT-001', '10.1.1.200','5', 'Cisco Catalyst 9200L',   '24-port PoE+ Managed Switch',       10, 4, 'MM', 1, 'IT Department',   '2022-03-10', 3200.00, '2027-03-10', 'active', 'good', 'not_applicable'),
('SN-MM-009', '00:1A:2B:3C:4D:09', 'MM-UPS-001', '10.1.1.201','9', 'APC Smart-UPS 3000VA',   '3kVA, LCD, Rack Mount 2U',          12, 5, 'MM', 1, 'Server Room',     '2021-08-15', 1650.00, '2026-08-15', 'active', 'fair', 'not_applicable'),
('SN-MM-010', NULL,                  'MM-LAP-004', '10.1.1.15', 1, 'Dell Latitude 3440',      '8GB RAM, 256GB SSD, i5-1345U',      1, 1, 'MM', 4, 'Tom Davis',       '2023-09-01', 920.00,  '2026-09-01', 'in_repair', 'poor', 'expired'),
('SN-MM-011', '00:1A:2B:3C:4D:0B', 'MM-PHN-001', '10.1.1.16', 6, 'Samsung Galaxy S24',       '256GB, 8GB RAM',                    9, 1, 'MM', 4, 'Amy Foster',      '2024-02-01', 850.00,  '2026-02-01', 'active', 'good', 'protected'),
('SN-MM-012', '00:1A:2B:3C:4D:0C', 'MM-DSK-002', '10.1.1.17', 2, 'HP ProDesk 400 G9',       '16GB RAM, 512GB SSD, i5-13500',     2, 1, 'MM', 2, 'Robert Lee',      '2022-05-20', 780.00,  '2025-05-20', 'active', 'fair', 'protected'),

-- ATL (Atlanta) — 8 assets
('SN-ATL-001', '00:2A:2B:3C:4D:01', 'ATL-LAP-001', '10.2.1.10', 1, 'Dell Latitude 5550',     '16GB RAM, 512GB SSD, Ultra 7',      1, 1, 'ATL', 5, 'Karen White',    '2024-08-10', 1520.00, '2027-08-10', 'active', 'new', 'protected'),
('SN-ATL-002', '00:2A:2B:3C:4D:02', 'ATL-LAP-002', '10.2.1.11', 3, 'Lenovo ThinkPad T14s',   '16GB RAM, 256GB SSD, Ryzen 7',      1, 1, 'ATL', 5, 'David Brown',    '2023-04-15', 1350.00, '2026-04-15', 'active', 'good', 'protected'),
('SN-ATL-003', '00:2A:2B:3C:4D:03', 'ATL-PRT-001', '10.2.1.50', 2, 'HP Color LaserJet Pro',  'Color, Duplex, WiFi',               5, 3, 'ATL', 6, 'Finance Dept',   '2023-02-01', 580.00,  '2026-02-01', 'active', 'good', 'not_applicable'),
('SN-ATL-004', '00:2A:2B:3C:4D:04', 'ATL-MON-001', '10.2.1.12', 6, 'Samsung 32" 4K',         '32" UHD, USB-C, HDR',               8, 6, 'ATL', 5, 'Karen White',    '2024-08-10', 480.00,  '2027-08-10', 'active', 'new', 'not_applicable'),
('SN-ATL-005', '00:2A:2B:3C:4D:05', 'ATL-LAP-003', '10.2.1.13', 4, 'Apple MacBook Air M3',   '16GB RAM, 256GB SSD',               1, 1, 'ATL', 7, 'Emily Clark',    '2024-05-20', 1300.00, '2027-05-20', 'active', 'new', 'protected'),
('SN-ATL-006', '00:2A:2B:3C:4D:06', 'ATL-RTR-001', '10.2.1.200','5','Cisco ISR 1100',         '4-port WAN, PoE',                   11, 4, 'ATL', 5, 'IT Closet A',    '2022-09-15', 2100.00, '2025-09-15', 'active', 'fair', 'not_applicable'),
('SN-ATL-007', '00:2A:2B:3C:4D:07', 'ATL-DSK-001', '10.2.1.14', 7, 'Microsoft Surface Pro 9','16GB RAM, 256GB SSD, i7',           1, 1, 'ATL', 5, 'James Wilson',   '2023-11-01', 1600.00, '2026-11-01', 'in_store', 'good', 'protected'),
('SN-ATL-008', '00:2A:2B:3C:4D:08', 'ATL-UPS-001', '10.2.1.201','9','APC Smart-UPS 1500VA',  '1.5kVA, LCD, Tower',                12, 5, 'ATL', 5, 'IT Closet A',    '2023-01-10', 890.00,  '2028-01-10', 'active', 'good', 'not_applicable'),

-- HRE (Harare) — 8 assets
('SN-HRE-001', '00:3A:2B:3C:4D:01', 'HRE-LAP-001', '10.3.1.10', 1, 'Dell Latitude 3540',    '8GB RAM, 256GB SSD, i5-1345U',      1, 1, 'HRE', 12, 'Tendai Moyo',   '2024-01-20', 980.00,  '2027-01-20', 'active', 'good', 'protected'),
('SN-HRE-002', '00:3A:2B:3C:4D:02', 'HRE-LAP-002', '10.3.1.11', 2, 'HP ProBook 450 G10',    '16GB RAM, 512GB SSD, i7',           1, 1, 'HRE', 12, 'Grace Chipo',   '2023-07-10', 1120.00, '2026-07-10', 'active', 'good', 'protected'),
('SN-HRE-003', '00:3A:2B:3C:4D:03', 'HRE-DSK-001', '10.3.1.12', 3, 'Lenovo ThinkCentre M90q','16GB RAM, 512GB SSD',              2, 1, 'HRE', 13, 'Peter Ncube',   '2023-03-01', 850.00,  '2026-03-01', 'active', 'fair', 'protected'),
('SN-HRE-004', '00:3A:2B:3C:4D:04', 'HRE-PRT-001', '10.3.1.50', 2, 'HP LaserJet M234sdw',   'Mono, Duplex, WiFi',                5, 3, 'HRE', 12, 'IT Dept HRE',   '2022-12-01', 320.00,  '2025-12-01', 'active', 'fair', 'not_applicable'),
('SN-HRE-005', '00:3A:2B:3C:4D:05', 'HRE-SWT-001', '10.3.1.200','10','Ubiquiti USW-24-PoE',  '24-port PoE Managed',               10, 4, 'HRE', 12, 'Server Room',   '2023-06-15', 580.00,  '2026-06-15', 'active', 'good', 'not_applicable'),
('SN-HRE-006', '00:3A:2B:3C:4D:06', 'HRE-AP-001',  '10.3.1.201','10','Ubiquiti U6-Pro',      'WiFi 6 Access Point',               13, 4, 'HRE', 12, 'Floor 2',       '2023-06-15', 180.00,  '2026-06-15', 'active', 'good', 'not_applicable'),
('SN-HRE-007', '00:3A:2B:3C:4D:07', 'HRE-LAP-003', '10.3.1.13', 1, 'Dell Latitude 5440',    '16GB RAM, 512GB SSD, i7',           1, 1, 'HRE', 14, 'Farai Mutasa',  '2022-08-01', 1400.00, '2025-08-01', 'disposed', 'poor', 'expired'),
('SN-HRE-008', '00:3A:2B:3C:4D:08', 'HRE-LAP-004', '10.3.1.14', 2, 'HP EliteBook 840 G10',  '16GB RAM, 512GB SSD, i7',           1, 1, 'HRE', 15, 'Simba Kuda',    '2024-09-01', 1550.00, '2027-09-01', 'in_transit', 'new', 'protected'),

-- PLD (Poland) — 6 assets
('SN-PLD-001', '00:4A:2B:3C:4D:01', 'PLD-LAP-001', '10.4.1.10', 3, 'Lenovo ThinkPad X1 Nano','16GB RAM, 512GB SSD',              1, 1, 'PLD', 18, 'Piotr Kowalski', '2024-04-01', 1780.00, '2027-04-01', 'active', 'new', 'protected'),
('SN-PLD-002', '00:4A:2B:3C:4D:02', 'PLD-LAP-002', '10.4.1.11', 1, 'Dell Latitude 7440',     '32GB RAM, 1TB SSD, i7',            1, 1, 'PLD', 18, 'Anna Nowak',     '2024-02-15', 2100.00, '2027-02-15', 'active', 'new', 'protected'),
('SN-PLD-003', '00:4A:2B:3C:4D:03', 'PLD-SRV-001', '10.4.1.100','2','HP ProLiant DL380 G10+', '64GB RAM, 8x1.2TB SAS RAID 6',    4, 2, 'PLD', 18, 'Server Room PL', '2022-06-01', 6800.00, '2027-06-01', 'active', 'good', 'not_applicable'),
('SN-PLD-004', '00:4A:2B:3C:4D:04', 'PLD-PRT-001', '10.4.1.50', 2, 'HP Color LaserJet M479', 'Color, Duplex, Scan, Fax',         5, 3, 'PLD', 19, 'Finance PL',     '2023-03-15', 650.00,  '2026-03-15', 'active', 'good', 'not_applicable'),
('SN-PLD-005', '00:4A:2B:3C:4D:05', 'PLD-MON-001', '10.4.1.12', 1, 'Dell P2723QE',           '27" 4K USB-C',                     8, 6, 'PLD', 18, 'Piotr Kowalski', '2024-04-01', 480.00,  '2027-04-01', 'active', 'new', 'not_applicable'),
('SN-PLD-006', '00:4A:2B:3C:4D:06', 'PLD-FW-001',  '10.4.1.200','5','Cisco Firepower 1010',  'NGFW, 8-port',                     14, 4, 'PLD', 18, 'Network Rack',   '2023-09-01', 3400.00, '2026-09-01', 'active', 'good', 'not_applicable'),

-- CHD, PSE, AVN, WLD — 4 assets each
('SN-CHD-001', '00:5A:2B:3C:4D:01', 'CHD-LAP-001', '10.5.1.10', 2, 'HP ProBook 440 G10',    '8GB RAM, 256GB SSD, i5',            1, 1, 'CHD', 10, 'Ibrahim Moussa', '2024-03-01', 890.00,  '2027-03-01', 'active', 'good', 'protected'),
('SN-CHD-002', '00:5A:2B:3C:4D:02', 'CHD-LAP-002', '10.5.1.11', 1, 'Dell Vostro 3520',      '8GB RAM, 256GB SSD, i5',            1, 1, 'CHD', 11, 'Aisha Deby',     '2023-11-15', 720.00,  '2026-11-15', 'active', 'good', 'protected'),
('SN-CHD-003', '00:5A:2B:3C:4D:03', 'CHD-PRT-001', '10.5.1.50', 2, 'HP LaserJet M110w',     'Mono, WiFi',                        5, 3, 'CHD', 10, 'IT Dept CHD',    '2023-05-01', 180.00,  '2026-05-01', 'active', 'fair', 'not_applicable'),
('SN-CHD-004', '00:5A:2B:3C:4D:04', 'CHD-UPS-001', '10.5.1.200','9','APC Back-UPS 1100VA',   '1.1kVA, Tower',                    12, 5, 'CHD', 10, 'IT Rack CHD',    '2022-08-01', 350.00,  '2025-08-01', 'active', 'fair', 'not_applicable'),

('SN-PSE-001', '00:6A:2B:3C:4D:01', 'PSE-LAP-001', '10.6.1.10', 3, 'Lenovo IdeaPad 5 Pro',  '16GB RAM, 512GB SSD, Ryzen 7',      1, 1, 'PSE', 16, 'Ahmad Khalil',   '2024-01-10', 1050.00, '2027-01-10', 'active', 'good', 'protected'),
('SN-PSE-002', '00:6A:2B:3C:4D:02', 'PSE-LAP-002', '10.6.1.11', 2, 'HP EliteBook 645 G10',  '16GB RAM, 256GB SSD, Ryzen 5',      1, 1, 'PSE', 17, 'Layla Nasser',   '2023-09-01', 1180.00, '2026-09-01', 'active', 'good', 'protected'),
('SN-PSE-003', '00:6A:2B:3C:4D:03', 'PSE-MON-001', '10.6.1.12', 6, 'Samsung 27" QHD',       '27" 2K, USB-C',                     8, 6, 'PSE', 16, 'Ahmad Khalil',   '2024-01-10', 350.00,  '2027-01-10', 'active', 'new', 'not_applicable'),
('SN-PSE-004', '00:6A:2B:3C:4D:04', 'PSE-RTR-001', '10.6.1.200','10','Ubiquiti Dream Machine', 'All-in-one Router/Switch/AP',     11, 4, 'PSE', 16, 'Network Cab',    '2023-04-01', 380.00,  '2026-04-01', 'active', 'good', 'not_applicable'),

('SN-AVN-001', '00:7A:2B:3C:4D:01', 'AVN-LAP-001', '10.7.1.10', 1, 'Dell Latitude 3440',    '8GB RAM, 256GB SSD, i5',            1, 1, 'AVN', 8, 'Chris Martinez', '2024-05-01', 920.00,  '2027-05-01', 'active', 'good', 'protected'),
('SN-AVN-002', '00:7A:2B:3C:4D:02', 'AVN-LAP-002', '10.7.1.11', 2, 'HP ProBook 450 G10',    '16GB RAM, 512GB SSD, i7',           1, 1, 'AVN', 9, 'Finance AVN',    '2023-08-15', 1120.00, '2026-08-15', 'active', 'good', 'protected'),
('SN-AVN-003', '00:7A:2B:3C:4D:03', 'AVN-PRT-001', '10.7.1.50', 2, 'HP Smart Tank 580',     'Ink Tank, WiFi, Color',             5, 3, 'AVN', 8, 'Shared Printer',  '2023-01-20', 250.00, '2026-01-20', 'active', 'fair', 'not_applicable'),
('SN-AVN-004', '00:7A:2B:3C:4D:04', 'AVN-AP-001',  '10.7.1.200','10','Ubiquiti U6-Lite',     'WiFi 6 Access Point',              13, 4, 'AVN', 8, 'Ceiling Mount',   '2023-06-01', 100.00, '2026-06-01', 'active', 'good', 'not_applicable'),

('SN-WLD-001', '00:8A:2B:3C:4D:01', 'WLD-LAP-001', '10.8.1.10', 1, 'Dell Rugged 5430',      '16GB RAM, 512GB SSD, Rugged',       1, 1, 'WLD', 21, 'Jake Thompson', '2024-06-01', 2400.00, '2027-06-01', 'active', 'new', 'protected'),
('SN-WLD-002', '00:8A:2B:3C:4D:02', 'WLD-LAP-002', '10.8.1.11', 3, 'Lenovo ThinkPad L15 G4','8GB RAM, 256GB SSD, Ryzen 5',       1, 1, 'WLD', 22, 'Field Ops Team', '2023-10-01', 880.00, '2026-10-01', 'active', 'good', 'protected'),
('SN-WLD-003', '00:8A:2B:3C:4D:03', 'WLD-TAB-001', '10.8.1.12', 6, 'Samsung Galaxy Tab S9', '12GB RAM, 256GB',                   3, 1, 'WLD', 22, 'Field Team A',   '2024-03-15', 750.00, '2027-03-15', 'active', 'good', 'protected'),
('SN-WLD-004', '00:8A:2B:3C:4D:04', 'WLD-RTR-001', '10.8.1.200','5','Cisco RV345',           'Dual WAN VPN Router',              11, 4, 'WLD', 21, 'Depot Network',  '2022-07-01', 450.00, '2025-07-01', 'active', 'fair', 'not_applicable');

-- ── SAMPLE SOFTWARE LICENSES ──
INSERT INTO public.software_licenses (name, vendor, license_type, total_seats, used_seats, purchase_date, expiry_date, cost) VALUES
('Microsoft 365 E3',          'Microsoft', 'subscription', 200, 156, '2024-01-01', '2025-12-31', 43200.00),
('Adobe Creative Cloud',      'Adobe',     'subscription', 15,  12,  '2024-06-01', '2025-05-31', 8100.00),
('Symantec Endpoint',         'Broadcom',  'subscription', 200, 180, '2024-03-01', '2025-02-28', 6000.00),
('AutoCAD 2024',              'Autodesk',  'perpetual',    5,   3,   '2024-01-15', NULL,         9500.00),
('Zoom Business',             'Zoom',      'subscription', 50,  42,  '2024-04-01', '2025-03-31', 2700.00);
